# Generated by Django 5.1.3 on 2025-12-07 13:03

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        db_index=True,
                        help_text="Unique session identifier (UUID)",
                        max_length=100,
                        unique=True,
                    ),
                ),
                (
                    "user_name",
                    models.CharField(
                        blank=True,
                        help_text="User's name collected during conversation",
                        max_length=200,
                    ),
                ),
                (
                    "current_state",
                    models.CharField(
                        choices=[
                            ("greeting", "Greeting"),
                            ("awaiting_name", "Awaiting Name"),
                            ("menu", "Menu"),
                            ("inquiry", "Inquiry"),
                            ("faq_mode", "FAQ Mode"),
                            ("dispute_mode", "Dispute Mode"),
                            ("feedback_mode", "Feedback Mode"),
                            ("chat_mode", "Chat Mode"),
                            ("escalation", "Escalation"),
                            ("resolution", "Resolution"),
                            ("feedback", "Feedback"),
                            ("closed", "Closed"),
                        ],
                        default="greeting",
                        help_text="Current conversation state",
                        max_length=20,
                    ),
                ),
                (
                    "context",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Complete session context: history, traits, sentiment, escalation, metadata",
                    ),
                ),
                (
                    "context_data",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Session context: order_id, seller_name, issue_type, etc.",
                    ),
                ),
                (
                    "conversation_history",
                    models.JSONField(
                        default=list,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="List of messages: [{role, content, timestamp}]",
                    ),
                ),
                (
                    "message_count",
                    models.IntegerField(
                        default=0, help_text="Number of messages in this session"
                    ),
                ),
                (
                    "sentiment_score",
                    models.FloatField(
                        default=0.5,
                        help_text="Overall sentiment (0=negative, 1=positive)",
                    ),
                ),
                (
                    "satisfaction_score",
                    models.FloatField(
                        default=0.5, help_text="User satisfaction estimate"
                    ),
                ),
                (
                    "escalation_level",
                    models.IntegerField(
                        default=0, help_text="Escalation level (0=none, 3=critical)"
                    ),
                ),
                (
                    "is_escalated",
                    models.BooleanField(
                        default=False,
                        help_text="Whether session has been escalated to human",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("last_activity", models.DateTimeField(auto_now=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        help_text="Authenticated user (optional)",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="conversation_sessions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_activity"],
            },
        ),
        migrations.CreateModel(
            name="ConversationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "anonymous_session_id",
                    models.CharField(
                        blank=True,
                        help_text="Anonymous session tracking for non-authenticated users",
                        max_length=100,
                    ),
                ),
                ("message", models.TextField(help_text="User's original message")),
                (
                    "rule_hit",
                    models.JSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Matched rule: {id, action, severity, matched_phrase}",
                        null=True,
                    ),
                ),
                (
                    "faq_hit",
                    models.JSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="FAQ match: {id, question, answer, score, method}",
                        null=True,
                    ),
                ),
                (
                    "llm_response",
                    models.TextField(blank=True, help_text="Raw LLM output if used"),
                ),
                (
                    "llm_meta",
                    models.JSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="LLM metadata: tokens, time_ms, model_name",
                        null=True,
                    ),
                ),
                ("final_reply", models.TextField(help_text="Reply sent to user")),
                (
                    "confidence",
                    models.FloatField(default=0.0, help_text="Confidence score (0-1)"),
                ),
                (
                    "explanation",
                    models.TextField(blank=True, help_text="Why this reply was chosen"),
                ),
                (
                    "processing_time_ms",
                    models.IntegerField(
                        default=0, help_text="Total processing time in milliseconds"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assistant_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated conversation session",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logs",
                        to="assistant.conversationsession",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Original user message that triggered the report"
                    ),
                ),
                (
                    "report_type",
                    models.CharField(
                        choices=[
                            ("dispute", "Dispute"),
                            ("complaint", "Complaint"),
                            ("feedback", "Feedback"),
                            ("suggestion", "Suggestion"),
                            ("bug", "Bug Report"),
                            ("scam", "Scam Report"),
                            ("other", "Other"),
                        ],
                        default="other",
                        help_text="Type of report (dispute, feedback, complaint, etc.)",
                        max_length=20,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="Report category (scam, payment, product, service, etc.)",
                        max_length=100,
                    ),
                ),
                (
                    "ai_generated_draft",
                    models.TextField(
                        blank=True,
                        help_text="AI-generated draft message for user to use when contacting seller/support",
                    ),
                ),
                (
                    "contact_preference",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("twitter", "Twitter"),
                            ("whatsapp", "WhatsApp"),
                            ("phone", "Phone"),
                            ("none", "None"),
                        ],
                        default="none",
                        help_text="User's preferred platform for contacting seller",
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("reviewing", "Reviewing"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "meta",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Additional context: matched_rule, conversation_log_id, seller_info, etc.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("admin_notes", models.TextField(blank=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "session",
                    models.ForeignKey(
                        blank=True,
                        help_text="Associated conversation session",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reports",
                        to="assistant.conversationsession",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assistant_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="conversationsession",
            index=models.Index(
                fields=["session_id"], name="assistant_c_session_6d654c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversationsession",
            index=models.Index(
                fields=["-last_activity"], name="assistant_c_last_ac_737d8d_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversationsession",
            index=models.Index(
                fields=["user", "-last_activity"], name="assistant_c_user_id_fee723_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversationsession",
            index=models.Index(
                fields=["is_escalated", "-last_activity"],
                name="assistant_c_is_esca_e86b5c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="conversationlog",
            index=models.Index(
                fields=["-created_at"], name="assistant_c_created_0c8e30_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversationlog",
            index=models.Index(
                fields=["user", "-created_at"], name="assistant_c_user_id_0094e2_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversationlog",
            index=models.Index(
                fields=["anonymous_session_id", "-created_at"],
                name="assistant_c_anonymo_587e3e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["-created_at"], name="assistant_r_created_970412_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["status", "severity"], name="assistant_r_status_aabff6_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="report",
            index=models.Index(
                fields=["report_type", "-created_at"],
                name="assistant_r_report__42d0db_idx",
            ),
        ),
    ]
