# Generated by Django 5.1.3 on 2026-02-18 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0005_conversationsession_assistant_mode'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='disputemedia',
            new_name='assistant_d_report__6a6b48_idx',
            old_name='assistant_di_report__be8e93_idx',
        ),
        migrations.RenameIndex(
            model_name='disputemedia',
            new_name='assistant_d_media_t_2bfdcf_idx',
            old_name='assistant_di_media_t_5f8391_idx',
        ),
        migrations.RenameIndex(
            model_name='disputemedia',
            new_name='assistant_d_retenti_9dd4bb_idx',
            old_name='assistant_di_retenti_7f20ee_idx',
        ),
        migrations.RenameIndex(
            model_name='disputemedia',
            new_name='assistant_d_report__ec1967_idx',
            old_name='assistant_di_report__ea97f2_idx',
        ),
        migrations.AlterField(
            model_name='conversationsession',
            name='assistant_lane',
            field=models.CharField(choices=[('inbox', 'Inbox Assistant'), ('customer_service', 'Customer Service Assistant')], default='inbox', help_text='Legacy assistant lane for backward compatibility', max_length=30),
        ),
    ]
