# Generated by ChatGPT Codex
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from django.core.serializers.json import DjangoJSONEncoder


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0006_rename_assistant_di_report__be8e93_idx_assistant_d_report__6a6b48_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('orders', '0001_initial'),
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DisputeTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_id', models.CharField(db_index=True, max_length=20, unique=True)),
                ('seller_type', models.CharField(choices=[('verified', 'Verified'), ('unverified', 'Unverified')], max_length=20)),
                ('dispute_category', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('desired_resolution', models.CharField(blank=True, max_length=255)),
                ('evidence_links', models.JSONField(blank=True, default=list, encoder=DjangoJSONEncoder)),
                ('status', models.CharField(choices=[('OPEN', 'Open')], default='OPEN', max_length=20)),
                ('ai_recommendation', models.TextField(blank=True, null=True)),
                ('admin_decision', models.TextField(blank=True, null=True)),
                ('risk_score', models.FloatField(blank=True, null=True)),
                ('seller_response_due_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispute_tickets_opened', to=settings.AUTH_USER_MODEL)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispute_tickets', to='orders.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dispute_tickets', to='market.product')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dispute_tickets_received', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DisputeTicketCommunication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sender_role', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('ai', 'AI'), ('admin', 'Admin'), ('system', 'System')], max_length=20)),
                ('channel', models.CharField(choices=[('chat', 'Chat'), ('email', 'Email'), ('system', 'System')], default='system', max_length=20)),
                ('message_type', models.CharField(default='note', max_length=40)),
                ('body', models.TextField(blank=True)),
                ('meta', models.JSONField(blank=True, default=dict, encoder=DjangoJSONEncoder)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='communications', to='assistant.disputeticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='disputeticket',
            index=models.Index(fields=['ticket_id'], name='assistant_di_ticket__7f8f8d_idx'),
        ),
        migrations.AddIndex(
            model_name='disputeticket',
            index=models.Index(fields=['status', '-created_at'], name='assistant_di_status_6600c3_idx'),
        ),
        migrations.AddIndex(
            model_name='disputeticket',
            index=models.Index(fields=['seller_type', '-created_at'], name='assistant_di_seller__be24bd_idx'),
        ),
        migrations.AddIndex(
            model_name='disputeticket',
            index=models.Index(fields=['buyer', '-created_at'], name='assistant_di_buyer_i_56eb5c_idx'),
        ),
        migrations.AddIndex(
            model_name='disputeticket',
            index=models.Index(fields=['seller', '-created_at'], name='assistant_di_seller__6bffca_idx'),
        ),
        migrations.AddIndex(
            model_name='disputeticketcommunication',
            index=models.Index(fields=['ticket', 'created_at'], name='assistant_di_ticket__26eb63_idx'),
        ),
        migrations.AddIndex(
            model_name='disputeticketcommunication',
            index=models.Index(fields=['sender_role', 'created_at'], name='assistant_di_sender__e37bdd_idx'),
        ),
    ]
