# Generated by Django 5.1.3 on 2026-03-01 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0014_recommendation_context_and_profiles'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='recommendationdemandgap',
            index=models.Index(
                fields=['requested_category', 'user', 'user_location'],
                name='demand_match_idx',
            ),
        ),
    ]
