# Generated by Django 5.1.3 on 2026-03-10 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0016_demandcluster'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='conversationsession',
            new_name='assistant_c_context_0aca1a_idx',
            old_name='assistant_co_context_96b742_idx',
        ),
        migrations.RenameIndex(
            model_name='conversationsession',
            new_name='assistant_c_assista_9e7778_idx',
            old_name='assistant_co_assista_286483_idx',
        ),
        migrations.RenameIndex(
            model_name='demandcluster',
            new_name='assistant_d_is_hot_ba2afe_idx',
            old_name='assistant_d_is_hot_d9a223_idx',
        ),
        migrations.RenameIndex(
            model_name='demandcluster',
            new_name='assistant_d_categor_b3aa1e_idx',
            old_name='assistant_d_categor_71f976_idx',
        ),
        migrations.RenameIndex(
            model_name='disputeauditlog',
            new_name='assistant_d_dispute_b6d77e_idx',
            old_name='assistant_d_dispute_9969c7_idx',
        ),
        migrations.RenameIndex(
            model_name='disputeauditlog',
            new_name='assistant_d_action__0469e1_idx',
            old_name='assistant_d_action__4b92d4_idx',
        ),
        migrations.RenameIndex(
            model_name='disputeticket',
            new_name='assistant_d_ticket__31ea75_idx',
            old_name='assistant_di_ticket__7f8f8d_idx',
        ),
        migrations.RenameIndex(
            model_name='disputeticket',
            new_name='assistant_d_status_3e2243_idx',
            old_name='assistant_di_status_6600c3_idx',
        ),
        migrations.RenameIndex(
            model_name='disputeticket',
            new_name='assistant_d_seller__dd0da1_idx',
            old_name='assistant_di_seller__be24bd_idx',
        ),
        migrations.RenameIndex(
            model_name='disputeticket',
            new_name='assistant_d_buyer_i_2c12c1_idx',
            old_name='assistant_di_buyer_i_56eb5c_idx',
        ),
        migrations.RenameIndex(
            model_name='disputeticket',
            new_name='assistant_d_seller__fb4694_idx',
            old_name='assistant_di_seller__6bffca_idx',
        ),
        migrations.RenameIndex(
            model_name='disputeticketcommunication',
            new_name='assistant_d_ticket__418f64_idx',
            old_name='assistant_di_ticket__26eb63_idx',
        ),
        migrations.RenameIndex(
            model_name='disputeticketcommunication',
            new_name='assistant_d_sender__f68e6f_idx',
            old_name='assistant_di_sender__e37bdd_idx',
        ),
        migrations.RenameIndex(
            model_name='recommendationdemandgap',
            new_name='assistant_r_request_32ea3e_idx',
            old_name='assistant_re_request_6cfad9_idx',
        ),
        migrations.RenameIndex(
            model_name='recommendationdemandgap',
            new_name='assistant_r_frequen_5a5af7_idx',
            old_name='assistant_re_frequen_4f6251_idx',
        ),
        migrations.RenameIndex(
            model_name='userbehaviorprofile',
            new_name='assistant_u_last_ag_aff153_idx',
            old_name='assistant_us_last_ag_4f82ab_idx',
        ),
        migrations.RenameIndex(
            model_name='userbehaviorprofile',
            new_name='assistant_u_ai_high_c8ee30_idx',
            old_name='assistant_us_ai_high_d434f8_idx',
        ),
    ]
