# Generated by Django 5.1.3 on 2026-03-21 23:49

import core.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0017_rename_assistant_co_context_96b742_idx_assistant_c_context_0aca1a_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disputemedia',
            name='file',
            field=models.FileField(storage=core.storage_backends.PrivateMediaStorage(), upload_to='private/disputes/%Y/%m/%d'),
        ),
    ]
