# Generated by Django 5.1.3 on 2026-04-29 23:58

import core.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assistant', '0018_alter_disputemedia_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='disputemedia',
            name='file',
            field=models.FileField(storage=core.storage_backends.PrivateMediaStorage(), upload_to='disputes/%Y/%m/%d'),
        ),
    ]
