# Generated by Django 5.1.3 on 2026-03-05 12:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_rename_market_prod_source_3fc319_idx_product_vie_source_d956a2_idx'),
        ('orders', '0003_order_refunded_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['seller'], name='order_items_seller__0dab98_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['order', 'seller'], name='order_items_order_i_364618_idx'),
        ),
    ]
