# Generated by Django 5.1.3 on 2026-01-24 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='deleted_at',
            field=models.DateTimeField(blank=True, db_index=True, editable=False, help_text='Timestamp when this record was soft-deleted', null=True),
        ),
    ]
