# Generated by Django 5.1.3 on 2026-02-18 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_productshareevent'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='productshareevent',
            new_name='product_sha_product_c89b9b_idx',
            old_name='product_sha_product_6f70d7_idx',
        ),
        migrations.RenameIndex(
            model_name='productshareevent',
            new_name='product_sha_user_id_01fc8a_idx',
            old_name='product_sha_user_id_158a7f_idx',
        ),
    ]
