# Generated by Django 5.1.3 on 2026-02-22 13:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_rename_product_sha_product_6f70d7_idx_product_sha_product_c89b9b_idx_and_more'),
        ('market', '0006_productvideo_security_scan_fields'),
    ]

    operations = [
    ]
