# Generated by Django 5.1.3 on 2026-02-23 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_merge_20260222_1421'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='productvideo',
            new_name='product_vid_product_6b28b2_idx',
            old_name='mkt_vid_scan_idx',
        ),
        migrations.RenameIndex(
            model_name='productview',
            new_name='product_vie_product_36019e_idx',
            old_name='product_view_product_user_idx',
        ),
    ]
