# Generated by Django 5.1.3 on 2026-03-05 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0011_rename_market_prod_source_3fc319_idx_product_vie_source_d956a2_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='embedding_vector',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
