# Generated by Django 5.1.3 on 2026-03-05 20:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0012_product_embedding_vector'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DemandEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('view', 'View'), ('favorite', 'Favorite'), ('cart_add', 'Cart Add'), ('purchase', 'Purchase'), ('search_interest', 'Search Interest')], db_index=True, max_length=20)),
                ('state', models.CharField(blank=True, default='', max_length=100)),
                ('lga', models.CharField(blank=True, default='', max_length=100)),
                ('source', models.CharField(blank=True, default='', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demand_events', to='market.product')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='market_demand_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'market_demand_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['product', 'event_type'], name='market_dema_product_8b11e1_idx'), models.Index(fields=['-created_at'], name='market_dema_created_585b57_idx'), models.Index(fields=['state', 'lga'], name='market_dema_state_cb0022_idx')],
            },
        ),
    ]
