# Generated by Django 5.1.3 on 2026-03-21 23:49

import core.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0013_demandevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(storage=core.storage_backends.PublicMediaStorage(), upload_to='public/products/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='thumbnail',
            field=models.ImageField(blank=True, storage=core.storage_backends.PublicMediaStorage(), upload_to='public/thumbnails/products/%Y/%m/'),
        ),
        migrations.AlterField(
            model_name='productvideo',
            name='video',
            field=models.FileField(storage=core.storage_backends.PublicMediaStorage(), upload_to='public/products/videos/%Y/%m/'),
        ),
    ]
