# Generated by Django 5.1.3 on 2026-04-27 01:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0014_alter_productimage_image_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='attributes',
            field=models.JSONField(blank=True, default=dict, help_text="Structured product attributes captured at upload time. Examples: {colour: 'Midnight Black', storage: '128GB', network: 'Unlocked', accessories: ['Charger', 'Box']}. Admin-verified before use in recommendations."),
        ),
        migrations.AddField(
            model_name='product',
            name='attributes_verified',
            field=models.BooleanField(default=False, help_text='Set True by admin after verifying attribute accuracy.'),
        ),
        migrations.AddField(
            model_name='product',
            name='attributes_verified_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='attributes_verified_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_products', to=settings.AUTH_USER_MODEL),
        ),
    ]
