# Generated by Django 5.1.3 on 2026-04-30 01:18

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0018_product_search_tags'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductFamily',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=140)),
                ('slug', models.SlugField(blank=True, max_length=160)),
                ('description', models.TextField(blank=True)),
                ('aliases', models.JSONField(blank=True, default=list)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('is_active', models.BooleanField(default=True)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subcategory_product_families', to='market.category')),
                ('top_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_families', to='market.category')),
            ],
            options={
                'db_table': 'product_families',
                'ordering': ['top_category__order', 'subcategory__order', 'order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='ProductAttributeSchema',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.SlugField(max_length=80)),
                ('label', models.CharField(max_length=120)),
                ('value_type', models.CharField(choices=[('text', 'Text'), ('number', 'Number'), ('decimal', 'Decimal'), ('boolean', 'Boolean'), ('select', 'Select'), ('multiselect', 'Multi-select'), ('date', 'Date'), ('list', 'List')], default='text', max_length=20)),
                ('required', models.BooleanField(default=False)),
                ('options', models.JSONField(blank=True, default=list)),
                ('unit', models.CharField(blank=True, max_length=40)),
                ('seller_prompt', models.CharField(blank=True, max_length=255)),
                ('examples', models.JSONField(blank=True, default=list)),
                ('search_weight', models.DecimalField(decimal_places=2, default=1.0, max_digits=4, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('filterable', models.BooleanField(default=True)),
                ('comparable', models.BooleanField(default=False)),
                ('order', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product_family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_schemas', to='market.productfamily')),
            ],
            options={
                'db_table': 'product_attribute_schemas',
                'ordering': ['product_family', 'order', 'key'],
            },
        ),
        migrations.AddField(
            model_name='product',
            name='product_family',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='market.productfamily'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['product_family', 'status'], name='products_product_186d29_idx'),
        ),
        migrations.AddIndex(
            model_name='productfamily',
            index=models.Index(fields=['top_category', 'is_active'], name='product_fam_top_cat_fbedca_idx'),
        ),
        migrations.AddIndex(
            model_name='productfamily',
            index=models.Index(fields=['subcategory', 'is_active'], name='product_fam_subcate_68d2ac_idx'),
        ),
        migrations.AddIndex(
            model_name='productfamily',
            index=models.Index(fields=['slug'], name='product_fam_slug_39bb1c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productfamily',
            unique_together={('top_category', 'subcategory', 'slug')},
        ),
        migrations.AddIndex(
            model_name='productattributeschema',
            index=models.Index(fields=['product_family', 'is_active'], name='product_att_product_43ec5d_idx'),
        ),
        migrations.AddIndex(
            model_name='productattributeschema',
            index=models.Index(fields=['key'], name='product_att_key_198836_idx'),
        ),
        migrations.AddIndex(
            model_name='productattributeschema',
            index=models.Index(fields=['required'], name='product_att_require_3a5559_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='productattributeschema',
            unique_together={('product_family', 'key')},
        ),
    ]
