# Generated by Django 5.1.3 on 2026-05-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0019_productfamily_productattributeschema_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url_locked',
            field=models.URLField(
                blank=True,
                default='',
                help_text=(
                    "Permanent URL for the product's assigned image. Must point to "
                    "Zunto-owned media storage and must not be recomputed from title."
                ),
                max_length=1000,
            ),
        ),
        migrations.AddField(
            model_name='product',
            name='image_source',
            field=models.CharField(
                blank=True,
                default='',
                help_text='One-time source metadata for the locked product image.',
                max_length=255,
            ),
        ),
    ]
