# Generated by Django 5.2.7 on 2025-11-04 00:24

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("market", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        help_text="Rating from 1 to 5 stars",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("comment", models.TextField()),
                (
                    "quality_rating",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Product quality rating",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "value_rating",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Value for money rating",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "accuracy_rating",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Description accuracy rating",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "is_verified_purchase",
                    models.BooleanField(
                        default=False,
                        help_text="Did reviewer actually purchase this product?",
                    ),
                ),
                ("is_approved", models.BooleanField(default=True)),
                ("is_flagged", models.BooleanField(default=False)),
                ("flagged_reason", models.TextField(blank=True)),
                ("helpful_count", models.PositiveIntegerField(default=0)),
                ("not_helpful_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="market.product",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_reviews_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "product_reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SellerReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "rating",
                    models.PositiveIntegerField(
                        help_text="Rating from 1 to 5 stars",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=200)),
                ("comment", models.TextField()),
                (
                    "communication_rating",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Communication rating",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "reliability_rating",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Reliability rating",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "professionalism_rating",
                    models.PositiveIntegerField(
                        blank=True,
                        help_text="Professionalism rating",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                (
                    "is_verified_transaction",
                    models.BooleanField(
                        default=False,
                        help_text="Did reviewer actually transact with this seller?",
                    ),
                ),
                ("is_approved", models.BooleanField(default=True)),
                ("is_flagged", models.BooleanField(default=False)),
                ("flagged_reason", models.TextField(blank=True)),
                ("helpful_count", models.PositiveIntegerField(default=0)),
                ("not_helpful_count", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="seller_reviews",
                        to="market.product",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seller_reviews_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        limit_choices_to={"role__in": ["seller", "service_provider"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seller_reviews_received",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "seller_reviews",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewResponse",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("response", models.TextField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product_review",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="response",
                        to="reviews.productreview",
                    ),
                ),
                (
                    "responder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_responses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seller_review",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="response",
                        to="reviews.sellerreview",
                    ),
                ),
            ],
            options={
                "db_table": "review_responses",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("image", models.ImageField(upload_to="reviews/%Y/%m/")),
                ("caption", models.CharField(blank=True, max_length=200)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product_review",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="reviews.productreview",
                    ),
                ),
                (
                    "seller_review",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="reviews.sellerreview",
                    ),
                ),
            ],
            options={
                "db_table": "review_images",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.CreateModel(
            name="ReviewHelpful",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "vote",
                    models.CharField(
                        choices=[
                            ("helpful", "Helpful"),
                            ("not_helpful", "Not Helpful"),
                        ],
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "product_review",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="helpful_votes",
                        to="reviews.productreview",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_votes",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "seller_review",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="helpful_votes",
                        to="reviews.sellerreview",
                    ),
                ),
            ],
            options={
                "db_table": "review_helpful_votes",
            },
        ),
        migrations.CreateModel(
            name="ReviewFlag",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("spam", "Spam"),
                            ("offensive", "Offensive Language"),
                            ("fake", "Fake Review"),
                            ("irrelevant", "Irrelevant Content"),
                            ("personal_info", "Contains Personal Information"),
                            ("other", "Other"),
                        ],
                        max_length=20,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("reviewing", "Under Review"),
                            ("resolved", "Resolved"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                (
                    "flagger",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="review_flags",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product_review",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flags",
                        to="reviews.productreview",
                    ),
                ),
                (
                    "seller_review",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flags",
                        to="reviews.sellerreview",
                    ),
                ),
            ],
            options={
                "db_table": "review_flags",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="productreview",
            index=models.Index(
                fields=["product", "-created_at"], name="product_rev_product_b958dd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="productreview",
            index=models.Index(
                fields=["reviewer", "-created_at"],
                name="product_rev_reviewe_076b45_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="productreview",
            index=models.Index(fields=["rating"], name="product_rev_rating_fb8943_idx"),
        ),
        migrations.AddIndex(
            model_name="productreview",
            index=models.Index(
                fields=["is_approved"], name="product_rev_is_appr_dbd189_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productreview",
            unique_together={("product", "reviewer")},
        ),
        migrations.AddIndex(
            model_name="sellerreview",
            index=models.Index(
                fields=["seller", "-created_at"], name="seller_revi_seller__d71bb4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="sellerreview",
            index=models.Index(
                fields=["reviewer", "-created_at"],
                name="seller_revi_reviewe_ff2dbd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="sellerreview",
            index=models.Index(fields=["rating"], name="seller_revi_rating_2c4ef4_idx"),
        ),
        migrations.AddIndex(
            model_name="sellerreview",
            index=models.Index(
                fields=["is_approved"], name="seller_revi_is_appr_f3781d_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="sellerreview",
            unique_together={("seller", "reviewer", "product")},
        ),
        migrations.AddIndex(
            model_name="reviewhelpful",
            index=models.Index(
                fields=["product_review", "user"], name="review_help_product_425774_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewhelpful",
            index=models.Index(
                fields=["seller_review", "user"], name="review_help_seller__a55113_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="reviewflag",
            index=models.Index(
                fields=["status", "-created_at"], name="review_flag_status_968b83_idx"
            ),
        ),
    ]
