# Generated by Django 5.1.3 on 2026-03-21 23:49

import core.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewimage',
            name='image',
            field=models.ImageField(storage=core.storage_backends.PublicMediaStorage(), upload_to='public/marketplace/reviews/%Y/%m/'),
        ),
    ]
