# Generated by Django 5.1.3 on 2026-04-29 23:58

import core.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0002_alter_reviewimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reviewimage',
            name='image',
            field=models.ImageField(storage=core.storage_backends.PublicMediaStorage(), upload_to='marketplace/reviews/%Y/%m/'),
        ),
    ]
