# Generated by Django 5.1.3 on 2025-12-07 13:03

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("market", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Conversation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "buyer",
                    models.ForeignKey(
                        help_text="The user initiating the conversation (buyer)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buying_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        default=1,
                        help_text="The product this conversation is about",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="conversations",
                        to="market.product",
                    ),
                ),
                (
                    "seller",
                    models.ForeignKey(
                        help_text="The user receiving the inquiry (seller)",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="selling_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "chat_conversations",
                "ordering": ["-updated_at"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("text", "Text Message"),
                            ("image", "Image"),
                            ("file", "File"),
                            ("voice", "Voice Note"),
                        ],
                        db_index=True,
                        default="text",
                        max_length=20,
                    ),
                ),
                (
                    "content",
                    models.TextField(
                        blank=True,
                        default="[No content]",
                        help_text="Text content or caption for attachments",
                    ),
                ),
                (
                    "attachment_url",
                    models.URLField(
                        blank=True,
                        help_text="S3/CDN URL for uploaded files",
                        max_length=500,
                        null=True,
                    ),
                ),
                (
                    "attachment_size",
                    models.PositiveIntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                (
                    "attachment_mime",
                    models.CharField(
                        blank=True,
                        help_text="MIME type of attachment (e.g., image/jpeg, audio/ogg)",
                        max_length=100,
                    ),
                ),
                (
                    "attachment_duration",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Duration in seconds (for voice notes/videos)",
                        max_digits=6,
                        null=True,
                    ),
                ),
                (
                    "waveform_data",
                    models.JSONField(
                        blank=True,
                        help_text="Array of amplitude values for waveform visualization",
                        null=True,
                    ),
                ),
                ("is_read", models.BooleanField(db_index=True, default=False)),
                ("read_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_at",
                    models.DateTimeField(
                        db_index=True, default=django.utils.timezone.now
                    ),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="chat.conversation",
                    ),
                ),
                (
                    "sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sent_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "chat_messages",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="MessageRead",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("read_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="read_receipts",
                        to="chat.message",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_reads",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "chat_message_reads",
                "ordering": ["-read_at"],
            },
        ),
        migrations.CreateModel(
            name="TypingIndicator",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "last_typed_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "conversation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="typing_indicators",
                        to="chat.conversation",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="typing_in",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "chat_typing_indicators",
                "ordering": ["-last_typed_at"],
            },
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["buyer", "-updated_at"], name="chat_conver_buyer_i_f4c815_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["seller", "-updated_at"], name="chat_conver_seller__993006_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["product"], name="chat_conver_product_3268e3_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="conversation",
            index=models.Index(
                fields=["-updated_at"], name="chat_conver_updated_6ee585_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="conversation",
            constraint=models.CheckConstraint(
                condition=models.Q(("buyer", models.F("seller")), _negated=True),
                name="different_users_in_conversation",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="conversation",
            unique_together={("buyer", "seller", "product")},
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "created_at"],
                name="chat_messag_convers_0a903c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["conversation", "is_read"],
                name="chat_messag_convers_390270_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["sender", "-created_at"], name="chat_messag_sender__5f8b49_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="message",
            index=models.Index(
                fields=["-created_at"], name="chat_messag_created_d42c5c_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="message",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("content__gt", ""), ("content__isnull", False)),
                    ("attachment_url__isnull", False),
                    _connector="OR",
                ),
                name="message_has_content_or_attachment",
            ),
        ),
        migrations.AddIndex(
            model_name="messageread",
            index=models.Index(
                fields=["message", "user"], name="chat_messag_message_d1f775_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="messageread",
            index=models.Index(
                fields=["user", "-read_at"], name="chat_messag_user_id_501dae_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="messageread",
            unique_together={("message", "user")},
        ),
        migrations.AlterUniqueTogether(
            name="typingindicator",
            unique_together={("conversation", "user")},
        ),
    ]
