# Generated by Django 5.1.3 on 2026-02-15 19:15

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_google_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('email', models.EmailField(db_index=True, max_length=254, unique=True)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phone', models.CharField(blank=True, max_length=17, null=True)),
                ('role', models.CharField(choices=[('buyer', 'Buyer'), ('seller', 'Seller'), ('service_provider', 'Service Provider'), ('delivery_rider', 'Delivery Rider'), ('admin', 'Admin')], default='buyer', max_length=20)),
                ('password_hash', models.CharField(max_length=128)),
                ('verification_code', models.CharField(max_length=6)),
                ('code_expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'pending_registrations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email'], name='pending_reg_email_a1f163_idx')],
            },
        ),
    ]
