# Generated by Django 5.1.3 on 2026-03-05 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_sellerprofile'),
        ('market', '0011_rename_market_prod_source_3fc319_idx_product_vie_source_d956a2_idx'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='sellerprofile',
            new_name='seller_prof_status_518810_idx',
            old_name='seller_prof_status_5c6689_idx',
        ),
        migrations.RenameIndex(
            model_name='sellerprofile',
            new_name='seller_prof_is_veri_4ce8f9_idx',
            old_name='seller_prof_is_veri_4eebf3_idx',
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='active_location',
            field=models.ForeignKey(blank=True, help_text='Canonical active location for seller listings.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='seller_profiles', to='market.location'),
        ),
    ]
