# Generated by Django 5.1.3 on 2026-03-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_rename_seller_prof_status_5c6689_idx_seller_prof_status_518810_idx_and_more'),
        ('market', '0013_demandevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='rating',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='total_reviews',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddIndex(
            model_name='sellerprofile',
            index=models.Index(fields=['verified'], name='seller_prof_verifie_0c892c_idx'),
        ),
        migrations.AddIndex(
            model_name='sellerprofile',
            index=models.Index(fields=['rating'], name='seller_prof_rating_2b1b27_idx'),
        ),
    ]
