# Generated by Django 5.1.3 on 2026-03-21 23:49

import core.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_sellerprofile_rating_sellerprofile_total_reviews_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=core.storage_backends.PublicMediaStorage(), upload_to='public/marketplace/profile_pictures/'),
        ),
    ]
