# Generated by Django 5.1.3 on 2026-04-29 23:58

import core.storage_backends
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_sellerprofile_ai_memory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_picture',
            field=models.ImageField(blank=True, null=True, storage=core.storage_backends.PublicMediaStorage(), upload_to='marketplace/profile_pictures/'),
        ),
    ]
