# Generated by Django 5.1.3 on 2026-05-11 11:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_repair_seeded_demo_accounts'),
        ('market', '0022_ensure_pgvector_extension_and_tables'),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerApplication',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('business_name', models.CharField(max_length=255)),
                ('business_type', models.CharField(choices=[('individual', 'Individual'), ('small_business', 'Small Business'), ('enterprise', 'Enterprise')], max_length=30)),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('phone', models.CharField(max_length=17)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seller_applications', to='market.category')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_application', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'seller_applications',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='seller_appl_status_011612_idx'), models.Index(fields=['created_at'], name='seller_appl_created_8969a9_idx')],
            },
        ),
    ]
