# Generated by Django 5.2.8 on 2025-11-29 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_orderitem_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='subtotal',
        ),
    ]
