# Generated by Django 5.1.3 on 2026-02-18 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0004_transactionconfirmation_pair_constraint'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='conversation',
            new_name='chat_conver_is_lock_88cc81_idx',
            old_name='chat_conver_is_lock_534ef9_idx',
        ),
        migrations.RenameIndex(
            model_name='transactionconfirmation',
            new_name='chat_transa_buyer_i_3a7f07_idx',
            old_name='chat_transa_buyer_i_b2b296_idx',
        ),
        migrations.RenameIndex(
            model_name='transactionconfirmation',
            new_name='chat_transa_seller__ca44b4_idx',
            old_name='chat_transa_seller__17d371_idx',
        ),
        migrations.RenameIndex(
            model_name='transactionconfirmation',
            new_name='chat_transa_product_3ccf3d_idx',
            old_name='chat_transa_product_070f6e_idx',
        ),
        migrations.RenameIndex(
            model_name='transactionconfirmation',
            new_name='chat_transa_status_d18ba7_idx',
            old_name='chat_transa_status_2084fe_idx',
        ),
    ]
