# Generated by Django 5.1.3 on 2025-11-30 13:57

import django.core.serializers.json
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ConversationLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "session_id",
                    models.CharField(
                        blank=True,
                        help_text="Anonymous session tracking for non-authenticated users",
                        max_length=100,
                    ),
                ),
                ("message", models.TextField(help_text="User's original message")),
                (
                    "rule_hit",
                    models.JSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Matched rule: {id, action, severity, matched_phrase}",
                        null=True,
                    ),
                ),
                (
                    "faq_hit",
                    models.JSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="FAQ match: {id, question, answer, score, method}",
                        null=True,
                    ),
                ),
                (
                    "llm_response",
                    models.TextField(blank=True, help_text="Raw LLM output if used"),
                ),
                (
                    "llm_meta",
                    models.JSONField(
                        blank=True,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="LLM metadata: tokens, time_ms, model_name",
                        null=True,
                    ),
                ),
                ("final_reply", models.TextField(help_text="Reply sent to user")),
                (
                    "confidence",
                    models.FloatField(default=0.0, help_text="Confidence score (0-1)"),
                ),
                (
                    "explanation",
                    models.TextField(blank=True, help_text="Why this reply was chosen"),
                ),
                (
                    "processing_time_ms",
                    models.IntegerField(
                        default=0, help_text="Total processing time in milliseconds"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assistant_conversations",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="assistant_c_created_0c8e30_idx"
                    ),
                    models.Index(
                        fields=["user", "-created_at"],
                        name="assistant_c_user_id_0094e2_idx",
                    ),
                    models.Index(
                        fields=["session_id", "-created_at"],
                        name="assistant_c_session_259916_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        help_text="Original user message that triggered the report"
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("reviewing", "Reviewing"),
                            ("resolved", "Resolved"),
                            ("closed", "Closed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "meta",
                    models.JSONField(
                        default=dict,
                        encoder=django.core.serializers.json.DjangoJSONEncoder,
                        help_text="Additional context: matched_rule, conversation_log_id, etc.",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("admin_notes", models.TextField(blank=True)),
                (
                    "resolved_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="resolved_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assistant_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["-created_at"], name="assistant_r_created_970412_idx"
                    ),
                    models.Index(
                        fields=["status", "severity"],
                        name="assistant_r_status_aabff6_idx",
                    ),
                ],
            },
        ),
    ]
