# Generated by Django 5.2.7 on 2025-11-07 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="product_name",
            field=models.CharField(default="products", max_length=255),
        ),
    ]
