# Generated by Django 5.2.7 on 2025-11-07 23:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0002_alter_orderitem_product_name"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="order",
            name="orders_custome_12b615_idx",
        ),
        migrations.RemoveIndex(
            model_name="order",
            name="orders_order_n_1336be_idx",
        ),
        migrations.RemoveIndex(
            model_name="order",
            name="orders_status_f8c8df_idx",
        ),
        migrations.RemoveIndex(
            model_name="order",
            name="orders_payment_5a5a3d_idx",
        ),
        migrations.RemoveIndex(
            model_name="orderitem",
            name="order_items_order_i_364618_idx",
        ),
        migrations.RemoveField(
            model_name="order",
            name="notes",
        ),
        migrations.RemoveField(
            model_name="order",
            name="payment_status",
        ),
        migrations.RemoveField(
            model_name="order",
            name="tracking_number",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="product_price",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="seller_name",
        ),
        migrations.RemoveField(
            model_name="orderitem",
            name="status",
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_address_ref",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="orders.shippingaddress",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="order_number",
            field=models.CharField(db_index=True, max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_address",
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_city",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name="order",
            name="shipping_state",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Payment"),
                    ("paid", "Paid"),
                    ("processing", "Processing"),
                    ("shipped", "Shipped"),
                    ("delivered", "Delivered"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="subtotal",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="product_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="orderitem",
            name="quantity",
            field=models.PositiveIntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
    ]
