# Generated by Django 5.2.7 on 2025-11-07 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0003_remove_order_orders_custome_12b615_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="tracking_number",
            field=models.CharField(
                blank=True,
                help_text="Shipping tracking number for the order",
                max_length=100,
                null=True,
            ),
        ),
    ]
