# Generated by Django 5.2.7 on 2025-11-14 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0007_order_payment_status_order_orders_payment_050188_idx"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderitem",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("shipped", "Shipped"),
                    ("cancelled", "Cancelled"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
