# Generated by Django 6.0.2 on 2026-02-05 18:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('cart', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserScore',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='cart_score', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('abandonment_score', models.DecimalField(decimal_places=2, default=0, help_text='Score based on abandonment frequency', max_digits=5)),
                ('value_score', models.DecimalField(decimal_places=2, default=0, help_text='Score based on average cart value', max_digits=5)),
                ('conversion_score', models.DecimalField(decimal_places=2, default=0, help_text='Score based on recovery/conversion rate', max_digits=5)),
                ('hesitation_score', models.DecimalField(decimal_places=2, default=0, help_text='Score based on time-to-abandon and save-for-later behavior', max_digits=5)),
                ('composite_score', models.DecimalField(decimal_places=2, default=0, help_text='Weighted composite score (0-100)', max_digits=5)),
                ('discount_eligibility', models.BooleanField(default=False, help_text='Whether user qualifies for targeted discounts')),
                ('recommended_discount', models.DecimalField(blank=True, decimal_places=2, default=0, help_text='Recommended discount percentage', max_digits=5, null=True)),
                ('promo_code', models.CharField(blank=True, help_text='Assigned promo code for this user', max_length=50, null=True)),
                ('last_calculated', models.DateTimeField(auto_now=True, db_index=True)),
            ],
            options={
                'db_table': 'user_scores',
                'ordering': ['-composite_score'],
                'indexes': [models.Index(fields=['-composite_score'], name='user_scores_composi_084ad2_idx'), models.Index(fields=['-value_score'], name='user_scores_value_s_7e7f2a_idx'), models.Index(fields=['last_calculated'], name='user_scores_last_ca_23502a_idx'), models.Index(fields=['discount_eligibility'], name='user_scores_discoun_9970a9_idx')],
            },
        ),
        migrations.CreateModel(
            name='CartEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(choices=[('cart_item_added', 'Item Added'), ('cart_item_updated', 'Item Updated'), ('cart_item_removed', 'Item Removed'), ('cart_item_saved', 'Item Saved for Later')], db_index=True, max_length=50)),
                ('cart_id', models.UUIDField(db_index=True)),
                ('data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'cart_events',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', '-created_at'], name='cart_events_event_t_a232c4_idx'), models.Index(fields=['user', '-created_at'], name='cart_events_user_id_768602_idx')],
            },
        ),
    ]
